const CLIENT_PORT = 3000;
const SERVER_PORT = 4000;
const RESTAURANT_PORT = 5000;
const DELIVERY_PORT = 6000;


module.exports = {
    CLIENT_PORT,
    SERVER_PORT,
    RESTAURANT_PORT,
    DELIVERY_PORT
}